# Generated by Django 4.2.2 on 2023-07-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0003_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='files',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
