# Generated by Django 4.2.2 on 2023-07-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0004_remove_uploadedfile_file_uploadedfile_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='created_at',
        ),
        migrations.AddField(
            model_name='project',
            name='file',
            field=models.FileField(default='', upload_to='project_files/'),
            preserve_default=False,
        ),
    ]
