# Generated by Django 4.2.2 on 2023-07-15 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signup',
            options={'verbose_name': 'Signup', 'verbose_name_plural': 'Signups'},
        ),
    ]
